-- MySQL Script generated by MySQL Workbench
-- Sun Oct 19 12:08:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Daily
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Daily` ;

-- -----------------------------------------------------
-- Schema Daily
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Daily` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Daily` ;

-- -----------------------------------------------------
-- Table `Daily`.`Actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`Actividades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`Actividades` (
  `ID_Actividad` INT UNIQUE AUTO_INCREMENT,
  `Nombre_Actividad` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_Actividad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Daily`.`Covers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`Covers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`Covers` (
  `ID_Covers` INT UNIQUE AUTO_INCREMENT,
  `Nombre_Usuarios` INT ZEROFILL NULL,
  `Cover_in` DATETIME NOT NULL,
  `Cover_Out` DATETIME NOT NULL,
  `Motivo` INT NULL,
  `Activo` VARCHAR(10) NULL,
  PRIMARY KEY (`ID_Covers`),
  INDEX `Motivo_idx` (`Motivo` ASC) VISIBLE,
  INDEX `Usuario_idx` (`Nombre_Usuarios` ASC) VISIBLE,
  CONSTRAINT `Motivo`
    FOREIGN KEY (`Motivo`)
    REFERENCES `Daily`.`motivo_id` (`id_motivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuario`
    FOREIGN KEY (`Nombre_Usuarios`)
    REFERENCES `Daily`.`Usuarios` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Daily`.`Estaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`Estaciones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`Estaciones` (
  `ID_Estaciones` INT UNIQUE AUTO_INCREMENT,
  `User_Logged` VARCHAR(100) NOT NULL,
  `Station_Number` INT NULL,
  PRIMARY KEY (`ID_Estaciones`),
  CONSTRAINT `estaciones_id`
    FOREIGN KEY (`Station_Number`)
    REFERENCES `Daily`.`estaciones_id` (`numero_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Daily`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`Eventos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`Eventos` (
  `ID_Eventos` INT UNIQUE AUTO_INCREMENT,
  `FechaHora` DATETIME NULL,
  `ID_Sitio` INT NULL,
  `Nombre_Actividad` INT NULL,
  `Cantidad` VARCHAR(45) NULL,
  `Camera` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(255) NULL,
  `ID_Usuario` INT NULL,
  `Eventoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Eventos`),
  INDEX `Sitio_idx` (`ID_Sitio` ASC) VISIBLE,
  INDEX `Actividad_idx` (`Nombre_Actividad` ASC) VISIBLE,
  INDEX `Usuario_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `Sitio`
    FOREIGN KEY (`ID_Sitio`)
    REFERENCES `Daily`.`Sitios` (`idSitios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Actividad`
    FOREIGN KEY (`Nombre_Actividad`)
    REFERENCES `Daily`.`Actividades` (`ID_Actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Daily`.`Sesiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`Sesiones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`Sesiones` (
  `ID_Sesion` INT UNIQUE AUTO_INCREMENT,
  `Nombre_Usuario` INT NULL,
  `Stations_ID` INT NULL,
  `Login_Time` DATETIME NULL,
  `Log_Out` DATETIME NULL,
  PRIMARY KEY (`ID_Sesion`),
  INDEX `Usuarios_idx` (`Nombre_Usuario` ASC) VISIBLE,
  CONSTRAINT `Usuarios`
    FOREIGN KEY (`Nombre_Usuario`)
    REFERENCES `Daily`.`Usuarios` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Daily`.`Sitios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`Sitios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`Sitios` (
  `idSitios` INT UNIQUE,
  `ID_Grupo` VARCHAR(255) NULL,
  `Nombre_sitio` VARCHAR(255) NULL,
  `Time_Zone` VARCHAR(45) NULL,
  PRIMARY KEY (`idSitios`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Daily`.`Specials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`Specials` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`Specials` (
  `ID_Special` INT UNIQUE AUTO_INCREMENT,
  `FechaHora` DATETIME NOT NULL,
  `ID_Sitio` INT NULL,
  `Nombre_Actividad` INT NULL,
  `Cantidad` VARCHAR(45) NOT NULL,
  `Camera` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `Usuario` INT NULL,
  `Time_Zone` INT NULL,
  `Supervisor` INT NULL,
  PRIMARY KEY (`ID_Special`),
  INDEX `Sitio_idx` (`ID_Sitio` ASC) VISIBLE,
  INDEX `Actividad_idx` (`Nombre_Actividad` ASC) VISIBLE,
  INDEX `Usuario_idx` (`Usuario` ASC) VISIBLE,
  INDEX `Time_zone_idx` (`Time_Zone` ASC) VISIBLE,
  INDEX `supervisor_idx` (`Supervisor` ASC) VISIBLE,
  CONSTRAINT `Specials_Sitio_fk`
    FOREIGN KEY (`ID_Sitio`)
    REFERENCES `Daily`.`Sitios` (`idSitios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `Specials_Actividad_fk`
  FOREIGN KEY (`Nombre_Actividad`)
  REFERENCES `Daily`.`Actividades` (`ID_Actividad`),

CONSTRAINT `Specials_Usuario_fk`
  FOREIGN KEY (`Usuario`)
  REFERENCES `Daily`.`Usuarios` (`ID_Usuario`),

CONSTRAINT `Specials_TimeZone_fk`
  FOREIGN KEY (`Time_Zone`)
  REFERENCES `Daily`.`Sitios` (`idSitios`),

CONSTRAINT `Specials_Supervisor_fk`
  FOREIGN KEY (`Supervisor`)
  REFERENCES `Daily`.`Usuarios` (`ID_Usuario`))

ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Daily`.`estaciones_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`estaciones_id` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`estaciones_id` (
  `id_station` INT UNIQUE AUTO_INCREMENT,
  `numero_estacion` INT NOT NULL,
  PRIMARY KEY (`id_station`),
  UNIQUE INDEX `numero_estacion_UNIQUE` (`numero_estacion` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Daily`.`motivo_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`motivo_id` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`motivo_id` (
  `id_motivo` INT UNIQUE AUTO_INCREMENT,
  `Motivo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_motivo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Daily`.`rol_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Daily`.`rol_id` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Daily`.`rol_id` (
  `id_rol` INT UNIQUE AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre_rol_UNIQUE` (`nombre_rol` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


